"""initial relational schema

Revision ID: 38c5cea16feb
Revises:
Create Date: 2026-08-23 12:41:20.719935
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "38c5cea16feb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("key", sa.String(length=160), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "athlete_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "running_phase",
            sa.Enum(
                "AEROBIC_BASE",
                "VOLUME_BUILD",
                "THRESHOLD_BUILD",
                "HALF_MARATHON_SPECIFIC",
                "MARATHON_SPECIFIC",
                "TAPER",
                "RECOVERY_TRANSITION",
                name="runningphase",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "climbing_phase",
            sa.Enum(
                "TECHNIQUE_VOLUME",
                "LIMIT_BOULDERING",
                "MAX_STRENGTH",
                "POWER",
                "POWER_ENDURANCE",
                "LEAD_SPECIFIC",
                "PERFORMANCE",
                "RECOVERY",
                name="climbingphase",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("current_half_marathon_seconds", sa.Integer(), nullable=False),
        sa.Column("baseline_monthly_distance_km", sa.Float(), nullable=False),
        sa.Column("long_term_monthly_distance_km", sa.Float(), nullable=False),
        sa.Column("stable_weekly_distance_min_km", sa.Float(), nullable=False),
        sa.Column("stable_weekly_distance_max_km", sa.Float(), nullable=False),
        sa.Column("half_marathon_goal_seconds", sa.Integer(), nullable=False),
        sa.Column("half_marathon_stretch_seconds", sa.Integer(), nullable=False),
        sa.Column("marathon_goal_seconds", sa.Integer(), nullable=False),
        sa.Column("tb2_verified_grade", sa.String(length=16), nullable=False),
        sa.Column("tb2_estimated_grade", sa.String(length=16), nullable=False),
        sa.Column("top_rope_current_grade", sa.String(length=16), nullable=False),
        sa.Column("tb2_long_term_goal", sa.String(length=32), nullable=False),
        sa.Column("outdoor_boulder_goal", sa.String(length=32), nullable=False),
        sa.Column("route_long_term_goal", sa.String(length=32), nullable=False),
        sa.Column("home_gym_name", sa.String(length=160), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "athlete_state_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state_type", sa.String(length=32), nullable=False),
        sa.Column("old_value", sa.String(length=80), nullable=False),
        sa.Column("new_value", sa.String(length=80), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["athlete_id"], ["athlete_profiles.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_athlete_state_history_changed_at"),
        "athlete_state_history",
        ["changed_at"],
        unique=False,
    )
    op.create_table(
        "training_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "primary_category",
            sa.Enum(
                "RUNNING", "CLIMBING", "STRENGTH_MOBILITY", name="notecategory", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=240), nullable=False),
        sa.Column("raw_input", sa.Text(), nullable=False),
        sa.Column("cleaned_note", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("key_takeaways", sa.JSON(), nullable=False),
        sa.Column("actionable_ideas", sa.JSON(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("source_title", sa.String(length=240), nullable=True),
        sa.Column("source_creator", sa.String(length=200), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "input_type",
            sa.Enum("TEXT", "VOICE", name="noteinputtype", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "classification_confidence",
            sa.Enum("LOW", "MODERATE", "HIGH", name="confidence", native_enum=False),
            nullable=False,
        ),
        sa.Column("use_for_coaching", sa.Boolean(), nullable=False),
        sa.Column("favorite", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_training_notes_primary_category"),
        "training_notes",
        ["primary_category"],
        unique=False,
    )
    op.create_table(
        "weekly_reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("week_end", sa.Date(), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("compliance", sa.JSON(), nullable=False),
        sa.Column("running", sa.JSON(), nullable=False),
        sa.Column("climbing", sa.JSON(), nullable=False),
        sa.Column("recovery", sa.JSON(), nullable=False),
        sa.Column("key_findings", sa.JSON(), nullable=False),
        sa.Column("next_week", sa.JSON(), nullable=False),
        sa.Column("narrative", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("week_start", name="uq_weekly_review_start"),
    )
    op.create_table(
        "coaching_principles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_note_id", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "RUNNING", "CLIMBING", "STRENGTH_MOBILITY", name="notecategory", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("principle", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("athlete_approved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_note_id"],
            ["training_notes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fatigue_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(length=120), nullable=True),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latent_by_domain", sa.JSON(), nullable=False),
        sa.Column("display_by_domain", sa.JSON(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "source_key", name="uq_fatigue_snapshot_source"),
    )
    op.create_index(
        op.f("ix_fatigue_snapshots_calculated_at"),
        "fatigue_snapshots",
        ["calculated_at"],
        unique=False,
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column(
            "goal_type",
            sa.Enum(
                "RUNNING_MILEAGE",
                "HALF_MARATHON",
                "MARATHON",
                "BOULDERING",
                "LEAD_CLIMBING",
                name="goaltype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("target_value", sa.String(length=160), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("current_status", sa.String(length=120), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_goals_one_current",
        "goals",
        ["athlete_id"],
        unique=True,
        sqlite_where=sa.text("is_current IS 1"),
    )
    op.create_table(
        "gym_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("gym", sa.String(length=160), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_gym_sets_one_active_per_gym",
        "gym_sets",
        ["athlete_id", "gym"],
        unique=True,
        sqlite_where=sa.text("is_active IS 1"),
    )
    op.create_table(
        "planned_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column(
            "sport",
            sa.Enum(
                "RUNNING",
                "CLIMBING",
                "STRENGTH",
                "CROSSFIT_CONDITIONING",
                "MOBILITY_RECOVERY",
                name="sport",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("workout_type", sa.String(length=80), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("planned_duration_minutes", sa.Float(), nullable=True),
        sa.Column("planned_distance_km", sa.Float(), nullable=True),
        sa.Column("target_rpe_min", sa.Float(), nullable=True),
        sa.Column("target_rpe_max", sa.Float(), nullable=True),
        sa.Column(
            "priority",
            sa.Enum("LOW", "NORMAL", "HIGH", name="sessionpriority", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "COMPLETED",
                "MODIFIED",
                "SKIPPED",
                "MOVED",
                "REPLACED",
                "REST",
                name="planstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("structured_blocks", sa.JSON(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("moved_from_id", sa.Integer(), nullable=True),
        sa.Column("replaced_session_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "target_rpe_max IS NULL OR (target_rpe_max >= 1 AND target_rpe_max <= 10)",
            name="ck_plan_target_rpe_max",
        ),
        sa.CheckConstraint(
            "target_rpe_min IS NULL OR (target_rpe_min >= 1 AND target_rpe_min <= 10)",
            name="ck_plan_target_rpe_min",
        ),
        sa.CheckConstraint(
            "target_rpe_min IS NULL OR target_rpe_max IS NULL OR target_rpe_min <= target_rpe_max",
            name="ck_plan_target_rpe_range",
        ),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["moved_from_id"],
            ["planned_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["replaced_session_id"],
            ["planned_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_planned_sessions_session_date"), "planned_sessions", ["session_date"], unique=False
    )
    op.create_index(op.f("ix_planned_sessions_sport"), "planned_sessions", ["sport"], unique=False)
    op.create_table(
        "readiness_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(length=120), nullable=True),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("running_score", sa.Float(), nullable=False),
        sa.Column(
            "running_label",
            sa.Enum("GOOD", "MODERATE", "LOW", name="readinesslabel", native_enum=False),
            nullable=False,
        ),
        sa.Column("climbing_score", sa.Float(), nullable=False),
        sa.Column(
            "climbing_label",
            sa.Enum("GOOD", "MODERATE", "LOW", name="readinesslabel", native_enum=False),
            nullable=False,
        ),
        sa.Column("components", sa.JSON(), nullable=False),
        sa.Column("subjective_delta", sa.Float(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("athlete_id", "source_key", name="uq_readiness_snapshot_source"),
    )
    op.create_index(
        op.f("ix_readiness_snapshots_calculated_at"),
        "readiness_snapshots",
        ["calculated_at"],
        unique=False,
    )
    op.create_table(
        "recovery_checkins",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sleep_duration_hours", sa.Float(), nullable=True),
        sa.Column("sleep_quality", sa.Integer(), nullable=True),
        sa.Column("energy", sa.Integer(), nullable=True),
        sa.Column("motivation", sa.Integer(), nullable=True),
        sa.Column("stress", sa.Integer(), nullable=True),
        sa.Column("general_soreness", sa.Float(), nullable=True),
        sa.Column("area_soreness", sa.JSON(), nullable=False),
        sa.Column("resting_hr", sa.Integer(), nullable=True),
        sa.Column("hrv", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recovery_checkins_recorded_at"), "recovery_checkins", ["recorded_at"], unique=False
    )
    op.create_table(
        "route_benchmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("benchmark_date", sa.Date(), nullable=False),
        sa.Column("top_rope_verified_grade", sa.String(length=16), nullable=True),
        sa.Column("lead_verified_grade", sa.String(length=16), nullable=True),
        sa.Column("target_grade", sa.String(length=16), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_route_benchmarks_benchmark_date"),
        "route_benchmarks",
        ["benchmark_date"],
        unique=False,
    )
    op.create_table(
        "running_fitness_estimates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("estimated_10k_seconds", sa.Float(), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum("LOW", "MODERATE", "HIGH", name="confidence", native_enum=False),
            nullable=False,
        ),
        sa.Column("source_event", sa.String(length=160), nullable=True),
        sa.Column("source_date", sa.Date(), nullable=True),
        sa.Column("formula", sa.String(length=200), nullable=True),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tb2_benchmarks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("benchmark_date", sa.Date(), nullable=False),
        sa.Column("board", sa.String(length=64), nullable=False),
        sa.Column("angle_degrees", sa.Integer(), nullable=False),
        sa.Column("verified_grade", sa.String(length=16), nullable=False),
        sa.Column("estimated_grade", sa.String(length=16), nullable=True),
        sa.Column("grade_scale", sa.String(length=32), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tb2_benchmarks_benchmark_date"), "tb2_benchmarks", ["benchmark_date"], unique=False
    )
    op.create_table(
        "threshold_estimates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column(
            "estimate_type",
            sa.Enum("LT1", "LT2", name="estimatetype", native_enum=False),
            nullable=False,
        ),
        sa.Column("pace_low_seconds_per_km", sa.Float(), nullable=True),
        sa.Column("pace_high_seconds_per_km", sa.Float(), nullable=True),
        sa.Column("hr_low", sa.Integer(), nullable=True),
        sa.Column("hr_high", sa.Integer(), nullable=True),
        sa.Column(
            "confidence",
            sa.Enum("LOW", "MODERATE", "HIGH", name="confidence", native_enum=False),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("measured_at", sa.Date(), nullable=False),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "completed_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("athlete_id", sa.Integer(), nullable=False),
        sa.Column("planned_session_id", sa.Integer(), nullable=True),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=True),
        sa.Column("duration_minutes", sa.Float(), nullable=False),
        sa.Column(
            "sport",
            sa.Enum(
                "RUNNING",
                "CLIMBING",
                "STRENGTH",
                "CROSSFIT_CONDITIONING",
                "MOBILITY_RECOVERY",
                name="sport",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("workout_type", sa.String(length=80), nullable=False),
        sa.Column("rpe", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("srpe_load", sa.Float(), nullable=True),
        sa.Column("base_stress", sa.Float(), nullable=True),
        sa.Column("ai_analysis", sa.JSON(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("duration_minutes > 0", name="ck_session_duration_positive"),
        sa.CheckConstraint("rpe IS NULL OR (rpe >= 1 AND rpe <= 10)", name="ck_session_rpe"),
        sa.ForeignKeyConstraint(
            ["athlete_id"],
            ["athlete_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["planned_session_id"],
            ["planned_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_completed_sessions_session_date"),
        "completed_sessions",
        ["session_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_completed_sessions_sport"), "completed_sessions", ["sport"], unique=False
    )
    op.create_table(
        "gym_set_colour_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gym_set_id", sa.Integer(), nullable=False),
        sa.Column("colour", sa.String(length=32), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("sent_count", sa.Integer(), nullable=False),
        sa.Column("available_problem_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["gym_set_id"], ["gym_sets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gym_set_id", "colour", name="uq_gym_set_colour"),
    )
    op.create_index(
        op.f("ix_gym_set_colour_progress_gym_set_id"),
        "gym_set_colour_progress",
        ["gym_set_id"],
        unique=False,
    )
    op.create_table(
        "planned_session_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("planned_session_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["planned_session_id"], ["planned_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("planned_session_id", "version", name="uq_plan_revision"),
    )
    op.create_index(
        op.f("ix_planned_session_revisions_planned_session_id"),
        "planned_session_revisions",
        ["planned_session_id"],
        unique=False,
    )
    op.create_table(
        "adaptation_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("affected_session_id", sa.Integer(), nullable=True),
        sa.Column("trigger_session_id", sa.Integer(), nullable=True),
        sa.Column("original_plan", sa.JSON(), nullable=False),
        sa.Column("proposed_plan", sa.JSON(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "KEEP",
                "REDUCE_VOLUME",
                "REDUCE_INTENSITY",
                "MOVE",
                "REPLACE",
                "ADD_RECOVERY",
                "PROGRESS",
                name="adaptationaction",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum("LOW", "MODERATE", "HIGH", name="confidence", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("RULE_ENGINE", "AI", "MANUAL", name="adaptationsource", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "decision",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "REJECTED",
                "EDITED",
                name="adaptationdecision",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["affected_session_id"],
            ["planned_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trigger_session_id"],
            ["completed_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "climbing_session_details",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("gym_or_crag", sa.String(length=200), nullable=True),
        sa.Column("hard_attempts", sa.Integer(), nullable=True),
        sa.Column("maximum_attempted", sa.String(length=32), nullable=True),
        sa.Column("maximum_sent", sa.String(length=32), nullable=True),
        sa.Column("grade_scale", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["completed_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "media_imports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("SCREENSHOT", "AUDIO", "TEXT", name="mediakind", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "UPLOADED",
                "EXTRACTED",
                "CONFIRMED",
                "FAILED",
                "DELETED",
                name="mediastatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(length=300), nullable=True),
        sa.Column("local_path", sa.String(length=1000), nullable=True),
        sa.Column("retain_raw", sa.Boolean(), nullable=False),
        sa.Column("extraction", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("confirmed_session_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_session_id"],
            ["completed_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "running_session_details",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column("average_pace_seconds_per_km", sa.Float(), nullable=True),
        sa.Column("average_hr", sa.Integer(), nullable=True),
        sa.Column("maximum_hr", sa.Integer(), nullable=True),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        sa.Column("cadence", sa.Float(), nullable=True),
        sa.Column("power_watts", sa.Float(), nullable=True),
        sa.Column("splits", sa.JSON(), nullable=False),
        sa.Column("intervals", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["completed_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "session_domain_stresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column(
            "domain",
            sa.Enum(
                "CARDIOVASCULAR",
                "LOWER_BODY",
                "FINGER_FOREARM",
                "PULLING_UPPER_BODY",
                "NEURAL",
                "SYSTEMIC",
                name="fatiguedomain",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("coefficient", sa.Float(), nullable=False),
        sa.Column("multiplier", sa.Float(), nullable=False),
        sa.Column("stress", sa.Float(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["completed_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "domain", name="uq_session_domain_stress"),
    )
    op.create_index(
        op.f("ix_session_domain_stresses_domain"),
        "session_domain_stresses",
        ["domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_domain_stresses_session_id"),
        "session_domain_stresses",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "strength_session_details",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("workout_name", sa.String(length=200), nullable=True),
        sa.Column("rounds", sa.Float(), nullable=True),
        sa.Column("result_time_seconds", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["completed_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "climbing_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("climbing_session_id", sa.Integer(), nullable=False),
        sa.Column("problem", sa.String(length=160), nullable=True),
        sa.Column("grade", sa.String(length=32), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("sent", sa.Boolean(), nullable=False),
        sa.Column("flash", sa.Boolean(), nullable=False),
        sa.Column("repeat", sa.Boolean(), nullable=False),
        sa.Column("project", sa.Boolean(), nullable=False),
        sa.Column("style_tags", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["climbing_session_id"], ["climbing_session_details.session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "strength_sets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strength_session_id", sa.Integer(), nullable=False),
        sa.Column("exercise", sa.String(length=160), nullable=False),
        sa.Column("set_count", sa.Integer(), nullable=True),
        sa.Column("reps", sa.Float(), nullable=True),
        sa.Column("load_kg", sa.Float(), nullable=True),
        sa.Column("rpe", sa.Float(), nullable=True),
        sa.Column("rir", sa.Float(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.CheckConstraint("rpe IS NULL OR (rpe >= 1 AND rpe <= 10)", name="ck_strength_set_rpe"),
        sa.ForeignKeyConstraint(
            ["strength_session_id"], ["strength_session_details.session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("strength_sets")
    op.drop_table("climbing_attempts")
    op.drop_table("strength_session_details")
    op.drop_index(
        op.f("ix_session_domain_stresses_session_id"), table_name="session_domain_stresses"
    )
    op.drop_index(op.f("ix_session_domain_stresses_domain"), table_name="session_domain_stresses")
    op.drop_table("session_domain_stresses")
    op.drop_table("running_session_details")
    op.drop_table("media_imports")
    op.drop_table("climbing_session_details")
    op.drop_table("adaptation_events")
    op.drop_index(
        op.f("ix_planned_session_revisions_planned_session_id"),
        table_name="planned_session_revisions",
    )
    op.drop_table("planned_session_revisions")
    op.drop_index(
        op.f("ix_gym_set_colour_progress_gym_set_id"), table_name="gym_set_colour_progress"
    )
    op.drop_table("gym_set_colour_progress")
    op.drop_index(op.f("ix_completed_sessions_sport"), table_name="completed_sessions")
    op.drop_index(op.f("ix_completed_sessions_session_date"), table_name="completed_sessions")
    op.drop_table("completed_sessions")
    op.drop_table("threshold_estimates")
    op.drop_index(op.f("ix_tb2_benchmarks_benchmark_date"), table_name="tb2_benchmarks")
    op.drop_table("tb2_benchmarks")
    op.drop_table("running_fitness_estimates")
    op.drop_index(op.f("ix_route_benchmarks_benchmark_date"), table_name="route_benchmarks")
    op.drop_table("route_benchmarks")
    op.drop_index(op.f("ix_recovery_checkins_recorded_at"), table_name="recovery_checkins")
    op.drop_table("recovery_checkins")
    op.drop_index(op.f("ix_readiness_snapshots_calculated_at"), table_name="readiness_snapshots")
    op.drop_table("readiness_snapshots")
    op.drop_index(op.f("ix_planned_sessions_sport"), table_name="planned_sessions")
    op.drop_index(op.f("ix_planned_sessions_session_date"), table_name="planned_sessions")
    op.drop_table("planned_sessions")
    op.drop_index(
        "uq_gym_sets_one_active_per_gym",
        table_name="gym_sets",
        sqlite_where=sa.text("is_active IS 1"),
    )
    op.drop_table("gym_sets")
    op.drop_index(
        "uq_goals_one_current", table_name="goals", sqlite_where=sa.text("is_current IS 1")
    )
    op.drop_table("goals")
    op.drop_index(op.f("ix_fatigue_snapshots_calculated_at"), table_name="fatigue_snapshots")
    op.drop_table("fatigue_snapshots")
    op.drop_table("coaching_principles")
    op.drop_table("weekly_reviews")
    op.drop_index(op.f("ix_training_notes_primary_category"), table_name="training_notes")
    op.drop_table("training_notes")
    op.drop_index(op.f("ix_athlete_state_history_changed_at"), table_name="athlete_state_history")
    op.drop_table("athlete_state_history")
    op.drop_table("athlete_profiles")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
